# Generated by Django 5.1.1 on 2024-09-20 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='T_material',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('m_name', models.TextField()),
                ('material', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='T_StorageQuizdb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student_db',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('s_first', models.CharField(max_length=255)),
                ('s_last', models.CharField(max_length=255)),
                ('section', models.CharField(max_length=255)),
                ('s_profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('s_student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='T_list_student_db',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='edumentor.student_db')),
            ],
        ),
        migrations.CreateModel(
            name='T_Quiz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('t_quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edumentor.t_storagequizdb')),
            ],
        ),
        migrations.CreateModel(
            name='T_student_scoresdb',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('STD_score', models.IntegerField()),
                ('name_studnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edumentor.t_list_student_db')),
                ('quiz_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edumentor.t_storagequizdb')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers_db',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('t_first', models.CharField(max_length=255)),
                ('t_last', models.CharField(max_length=255)),
                ('t_subject', models.CharField(max_length=255)),
                ('t_profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('t_student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='t_list_student_db',
            name='teachers',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='edumentor.teachers_db'),
        ),
        migrations.CreateModel(
            name='Student_subject_db',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('Teachers_db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edumentor.teachers_db')),
            ],
        ),
    ]
