# Generated by Django 5.1.1 on 2024-09-20 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edumentor', '0002_alter_t_list_student_db_teachers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='chat_bot_AI',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bot_chat', models.TextField()),
                ('time', models.TimeField()),
                ('base_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='chat_bot_User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_chat', models.CharField(max_length=255)),
                ('time', models.TimeField()),
                ('base_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
